# Generated by Django 3.2.20 on 2023-08-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_auto_20230827_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(null=True),
        ),
    ]
